Added the tier name, current and max level message
Guillaume-Lebegue/IslandUpgrades pull request #30
Opened 2020-11-01 11:21 UTC by king-glitch

Added the tier name, current and max level message

2020-11-01 19:44 UTC, Guillaume-Lebegue commented
Thanks for doing that, kinda forgot about it when developing it.
I'm ok with most of the changes.
However, I'm not ok with the update from " to ' in the local file as the rest of BentoBox is using "

2020-11-02 12:04 UTC, king-glitch commented
> Thanks for doing that, kinda forgot about it when developing it.
> I'm ok with most of the changes.
> However, I'm not ok with the update from " to ' in the local file as the rest of BentoBox is using "

Sorry, it was my auto format. And I'm very newbie on Java. Thank you for teaching me good pratices!

2020-11-02 16:55 UTC, Guillaume-Lebegue requested changes
Don't worry about that.
Just a little thing before the approval

2020-11-02 16:55 UTC, Guillaume-Lebegue commented on src/main/resources/locales/en-US.yml
> +            description: "Switch who can upgrade"
That's close,
YAML advises to use 2 spaces for indentation

If you want, you can use websites like http://www.yamllint.com/ to check .yml files

2020-11-04 08:31 UTC, Guillaume-Lebegue approved these changes
Thx, that's good for me.

2020-11-12 19:53 UTC, merged